# DOCKER-VERSION 0.4.0
FROM  ubuntu:12.04
RUN   apt-get update
RUN   apt-get install -y python-software-properties python g++ make
RUN   add-apt-repository -y ppa:chris-lea/node.js
RUN   apt-get update
